import type { Route } from "../game/model/types";

export const europeRoutes: Route[] = [
  {
    id: "lisboa-madrid",
    cityA: "lisboa",
    cityB: "madrid",
    length: 3,
    color: "purple",
    extra: false,
  },
  {
    id: "lisboa-cadiz",
    cityA: "lisboa",
    cityB: "cadiz",
    length: 2,
    color: "blue",
    extra: false,
  },
  {
    id: "cadiz-madrid",
    cityA: "cadiz",
    cityB: "madrid",
    length: 3,
    color: "orange",
    extra: false,
  },
  {
    id: "madrid-pamplona-a",
    cityA: "madrid",
    cityB: "pamplona",
    length: 3,
    color: "white",
    extra: true,
    parallelGroupId: "madrid-pamplona-double",
  },
  {
    id: "madrid-pamplona-b",
    cityA: "madrid",
    cityB: "pamplona",
    length: 3,
    color: "black",
    extra: true,
    parallelGroupId: "madrid-pamplona-double",
  },
  {
    id: "madrid-barcelona",
    cityA: "madrid",
    cityB: "barcelona",
    length: 2,
    color: "yellow",
    extra: false,
  },
  {
    id: "barcelona-pamplona",
    cityA: "barcelona",
    cityB: "pamplona",
    length: 2,
    color: "gray",
    extra: true,
  },
  {
    id: "barcelona-marseille",
    cityA: "barcelona",
    cityB: "marseille",
    length: 4,
    color: "gray",
    extra: false,
  },
  {
    id: "marseille-pamplona",
    cityA: "marseille",
    cityB: "pamplona",
    length: 4,
    color: "red",
    extra: false,
  },
  {
    id: "paris-pamplona-a",
    cityA: "paris",
    cityB: "pamplona",
    length: 4,
    color: "blue",
    extra: false,
    parallelGroupId: "paris-pamplona-double",
  },
  {
    id: "paris-pamplona-b",
    cityA: "paris",
    cityB: "pamplona",
    length: 4,
    color: "green",
    extra: false,
    parallelGroupId: "paris-pamplona-double",
  },
  {
    id: "brest-pamplona",
    cityA: "brest",
    cityB: "pamplona",
    length: 4,
    color: "purple",
    extra: false,
  },
  {
    id: "brest-dieppe",
    cityA: "brest",
    cityB: "dieppe",
    length: 2,
    color: "orange",
    extra: false,
  },
  {
    id: "brest-paris",
    cityA: "brest",
    cityB: "paris",
    length: 3,
    color: "green",
    extra: false,
  },
  {
    id: "dieppe-paris",
    cityA: "dieppe",
    cityB: "paris",
    length: 1,
    color: "black",
    extra: false,
  },
  {
    id: "dieppe-london-a",
    cityA: "dieppe",
    cityB: "london",
    length: 2,
    color: "gray",
    extra: false,
    parallelGroupId: "dieppe-london-double",
  },
  {
    id: "dieppe-london-b",
    cityA: "dieppe",
    cityB: "london",
    length: 2,
    color: "black",
    extra: true,
    parallelGroupId: "dieppe-london-double",
  },
  {
    id: "london-edinburgh-a",
    cityA: "london",
    cityB: "edinburgh",
    length: 4,
    color: "black",
    extra: false,
    parallelGroupId: "london-edinburgh-double",
  },
  {
    id: "london-edinburgh-b",
    cityA: "london",
    cityB: "edinburgh",
    length: 4,
    color: "orange",
    extra: false,
    parallelGroupId: "london-edinburgh-double",
  },
  {
    id: "london-amsterdam",
    cityA: "london",
    cityB: "amsterdam",
    length: 2,
    color: "black",
    extra: false,
  },
  {
    id: "paris-marseille",
    cityA: "paris",
    cityB: "marseille",
    length: 4,
    color: "gray",
    extra: false,
  },
  {
    id: "paris-bruxelles-a",
    cityA: "paris",
    cityB: "bruxelles",
    length: 2,
    color: "yellow",
    extra: true,
    parallelGroupId: "paris-bruxelles-double",
  },
  {
    id: "paris-bruxelles-b",
    cityA: "paris",
    cityB: "bruxelles",
    length: 2,
    color: "red",
    extra: true,
    parallelGroupId: "paris-bruxelles-double",
  },
  {
    id: "paris-frankfurt-a",
    cityA: "paris",
    cityB: "frankfurt",
    length: 3,
    color: "white",
    extra: false,
    parallelGroupId: "paris-frankfurt-double",
  },
  {
    id: "paris-frankfurt-b",
    cityA: "paris",
    cityB: "frankfurt",
    length: 3,
    color: "green",
    extra: true,
    parallelGroupId: "paris-frankfurt-double",
  },
  {
    id: "paris-zurich",
    cityA: "paris",
    cityB: "frankfurt",
    length: 3,
    color: "black",
    extra: true,
  },
  {
    id: "bruxelles-amsterdam",
    cityA: "bruxelles",
    cityB: "amsterdam",
    length: 1,
    color: "yellow",
    extra: true,
  },
  {
    id: "bruxelles-frankfurt",
    cityA: "bruxelles",
    cityB: "frankfurt",
    length: 2,
    color: "blue",
    extra: false,
  },
  {
    id: "marseille-zurich",
    cityA: "marseille",
    cityB: "zurich",
    length: 2,
    color: "purple",
    extra: true,
  },
  {
    id: "amsterdam-essen",
    cityA: "amsterdam",
    cityB: "essen",
    length: 3,
    color: "yellow",
    extra: false,
  },
  {
    id: "amsterdam-frankfurt",
    cityA: "amsterdam",
    cityB: "frankfurt",
    length: 2,
    color: "yellow",
    extra: true,
  },
  {
    id: "marseille-roma",
    cityA: "marseille",
    cityB: "roma",
    length: 4,
    color: "black",
    extra: true,
  },
  {
    id: "zurich-venezia",
    cityA: "zurich",
    cityB: "venezia",
    length: 2,
    color: "green",
    extra: true,
  },
  {
    id: "zurich-munchen",
    cityA: "zurich",
    cityB: "munchen",
    length: 2,
    color: "yellow",
    extra: true,
  },
  {
    id: "frankfurt-munchen",
    cityA: "frankfurt",
    cityB: "munchen",
    length: 2,
    color: "yellow",
    extra: false,
  },
  {
    id: "essen-kobenhavn",
    cityA: "essen",
    cityB: "kobenhavn",
    length: 3,
    color: "gray",
    extra: false,
  },
  {
    id: "stockholm-kobenhavn-a",
    cityA: "stockholm",
    cityB: "kobenhavn",
    length: 3,
    color: "white",
    extra: false,
    parallelGroupId: "stockholm-kobenhavn-double",
  },
  {
    id: "stockholm-kobenhavn-b",
    cityA: "stockholm",
    cityB: "kobenhavn",
    length: 3,
    color: "yellow",
    extra: false,
    parallelGroupId: "stockholm-kobenhavn-double",
  },
  {
    id: "essen-berlin",
    cityA: "essen",
    cityB: "berlin",
    length: 2,
    color: "blue",
    extra: false,
  },
  {
    id: "frankfurt-essen",
    cityA: "essen",
    cityB: "frankfurt",
    length: 2,
    color: "green",
    extra: false,
  },
  {
    id: "frankfurt-berlin-a",
    cityA: "berlin",
    cityB: "frankfurt",
    length: 3,
    color: "black",
    extra: false,
    parallelGroupId: "frankfurt-berlin-double",
  },
  {
    id: "frankfurt-berlin-b",
    cityA: "berlin",
    cityB: "frankfurt",
    length: 3,
    color: "red",
    extra: false,
    parallelGroupId: "frankfurt-berlin-double",
  },
  {
    id: "munchen-wien",
    cityA: "munchen",
    cityB: "wien",
    length: 3,
    color: "orange",
    extra: false,
  },
  {
    id: "munchen-venezia",
    cityA: "munchen",
    cityB: "venezia",
    length: 2,
    color: "blue",
    extra: true,
  },
  {
    id: "roma-venezia",
    cityA: "roma",
    cityB: "venezia",
    length: 2,
    color: "black",
    extra: false,
  },
  {
    id: "roma-brindisi",
    cityA: "roma",
    cityB: "brindisi",
    length: 2,
    color: "black",
    extra: false,
  },
  {
    id: "roma-palermo",
    cityA: "roma",
    cityB: "palermo",
    length: 4,
    color: "gray",
    extra: false,
  },
  {
    id: "palermo-brindisi",
    cityA: "palermo",
    cityB: "brindisi",
    length: 3,
    color: "gray",
    extra: false,
  },
  {
    id: "athina-brindisi",
    cityA: "athina",
    cityB: "brindisi",
    length: 4,
    color: "gray",
    extra: false,
  },
  {
    id: "palermo-smyrna",
    cityA: "palermo",
    cityB: "smyrna",
    length: 6,
    color: "gray",
    extra: false,
  },
  {
    id: "berlin-danzig",
    cityA: "berlin",
    cityB: "danzig",
    length: 4,
    color: "yellow",
    extra: false,
  },
  {
    id: "berlin-warszawa-a",
    cityA: "berlin",
    cityB: "warszawa",
    length: 4,
    color: "yellow",
    extra: false,
    parallelGroupId: "berlin-warszawa-double",
  },
  {
    id: "berlin-warszawa-b",
    cityA: "berlin",
    cityB: "warszawa",
    length: 4,
    color: "purple",
    extra: false,
    parallelGroupId: "berlin-warszawa-double",
  },
  {
    id: "berlin-wien",
    cityA: "berlin",
    cityB: "wien",
    length: 3,
    color: "green",
    extra: false,
  },
  {
    id: "berlin-wien",
    cityA: "berlin",
    cityB: "wien",
    length: 3,
    color: "green",
    extra: false,
  },
  {
    id: "venezia-zagrab",
    cityA: "venezia",
    cityB: "zagrab",
    length: 2,
    color: "gray",
    extra: false,
  },
  {
    id: "wien-warszawa",
    cityA: "wien",
    cityB: "warszawa",
    length: 4,
    color: "blue",
    extra: false,
  },
  {
    id: "wien-budapest-a",
    cityA: "wien",
    cityB: "budapest",
    length: 1,
    color: "red",
    extra: false,
    parallelGroupId: "wien-budapest-double",
  },
  {
    id: "wien-budapest-b",
    cityA: "wien",
    cityB: "budapest",
    length: 1,
    color: "white",
    extra: false,
    parallelGroupId: "wien-budapest-double",
  },
  {
    id: "wien-zagrab",
    cityA: "wien",
    cityB: "zagrab",
    length: 2,
    color: "green",
    extra: false,
  },
  {
    id: "budapest-zagrab",
    cityA: "budapest",
    cityB: "zagrab",
    length: 2,
    color: "orange",
    extra: false,
  },
  {
    id: "sarajevo-zagrab",
    cityA: "sarajevo",
    cityB: "zagrab",
    length: 3,
    color: "red",
    extra: false,
  },
  {
    id: "budapest-sarajevo",
    cityA: "budapest",
    cityB: "sarajevo",
    length: 3,
    color: "purple",
    extra: false,
  },
  {
    id: "budapest-kyiv",
    cityA: "budapest",
    cityB: "kyiv",
    length: 6,
    color: "gray",
    extra: true,
  },
  {
    id: "budapest-bucuresti",
    cityA: "budapest",
    cityB: "bucuresti",
    length: 4,
    color: "gray",
    extra: true,
  },
  {
    id: "danzig-riga",
    cityA: "danzig",
    cityB: "riga",
    length: 3,
    color: "black",
    extra: false,
  },
  {
    id: "danzig-warszawa",
    cityA: "danzig",
    cityB: "warszawa",
    length: 2,
    color: "gray",
    extra: false,
  },
  {
    id: "wilno-warszawa",
    cityA: "wilno",
    cityB: "warszawa",
    length: 3,
    color: "red",
    extra: false,
  },
   {
    id: "kyiv-warszawa",
    cityA: "kyiv",
    cityB: "warszawa",
    length: 4,
    color: "gray",
    extra: false,
  },
  {
    id: "riga-wilno",
    cityA: "riga",
    cityB: "wilno",
    length: 4,
    color: "green",
    extra: false,
  },
  {
    id: "sarajevo-sofia",
    cityA: "sarajevo",
    cityB: "sofia",
    length: 2,
    color: "gray",
    extra: true,
  },
  {
    id: "sarajevo-athina",
    cityA: "sarajevo",
    cityB: "athina",
    length: 4,
    color: "green",
    extra: false,
  },
  {
    id: "athina-sofia",
    cityA: "athina",
    cityB: "sofia",
    length: 3,
    color: "purple",
    extra: false,
  },
  {
    id: "athina-smyrna",
    cityA: "athina",
    cityB: "smyrna",
    length: 2,
    color: "gray",
    extra: false,
  },
  {
    id: "bucuresti-sofia",
    cityA: "bucuresti",
    cityB: "sofia",
    length: 2,
    color: "gray",
    extra: true,
  },
  {
    id: "bucuresti-kyiv",
    cityA: "bucuresti",
    cityB: "kyiv",
    length: 4,
    color: "gray",
    extra: false,
  },
  {
    id: "kyiv-wilno",
    cityA: "kyiv",
    cityB: "wilno",
    length: 2,
    color: "gray",
    extra: false,
  },
  {
    id: "petrograd-stockholm",
    cityA: "petrograd",
    cityB: "stockholm",
    length: 8,
    color: "gray",
    extra: true,
  },
  {
    id: "petrograd-riga",
    cityA: "petrograd",
    cityB: "riga",
    length: 4,
    color: "gray",
    extra: false,
  },
  {
    id: "petrograd-wilno",
    cityA: "petrograd",
    cityB: "wilno",
    length: 4,
    color: "blue",
    extra: false,
  },
  {
    id: "petrograd-moskva",
    cityA: "petrograd",
    cityB: "moskva",
    length: 4,
    color: "white",
    extra: false,
  },
  {
    id: "smolensk-moskva",
    cityA: "smolensk",
    cityB: "moskva",
    length: 2,
    color: "orange",
    extra: false,
  },
  {
    id: "smolensk-wilno",
    cityA: "smolensk",
    cityB: "wilno",
    length: 3,
    color: "yellow",
    extra: false,
  },
  {
    id: "smolensk-kyiv",
    cityA: "smolensk",
    cityB: "kyiv",
    length: 3,
    color: "red",
    extra: false,
  },
  {
    id: "kharkiv-moskva",
    cityA: "kharkiv",
    cityB: "moskva",
    length: 4,
    color: "gray",
    extra: false,
  },
  {
    id: "kharkiv-kyiv",
    cityA: "kharkiv",
    cityB: "kyiv",
    length: 4,
    color: "gray",
    extra: false,
  },
  {
    id: "kharkiv-rostov",
    cityA: "kharkiv",
    cityB: "rostov",
    length: 2,
    color: "green",
    extra: false,
  },
  {
    id: "sevastopol-rostov",
    cityA: "sevastopol",
    cityB: "rostov",
    length: 3,
    color: "gray",
    extra: false,
  },
  {
    id: "sochi-rostov",
    cityA: "sochi",
    cityB: "rostov",
    length: 2,
    color: "gray",
    extra: false,
  },
  {
    id: "sochi-sevastopol",
    cityA: "sochi",
    cityB: "sevastopol",
    length: 2,
    color: "gray",
    extra: false,
  },
  {
    id: "sochi-erzurum",
    cityA: "sochi",
    cityB: "erzurum",
    length: 3,
    color: "red",
    extra: true,
  },
  {
    id: "sevastopol-erzurum",
    cityA: "sevastopol",
    cityB: "erzurum",
    length: 4,
    color: "gray",
    extra: false,
  },
  {
    id: "angora-erzurum",
    cityA: "angora",
    cityB: "erzurum",
    length: 3,
    color: "black",
    extra: false,
  },
  {
    id: "angora-smyrna",
    cityA: "angora",
    cityB: "smyrna",
    length: 3,
    color: "orange",
    extra: true,
  },
  {
    id: "angora-constantinople",
    cityA: "angora",
    cityB: "constantinople",
    length: 2,
    color: "gray",
    extra: true,
  },
  {
    id: "smyrna-constantinople",
    cityA: "smyrna",
    cityB: "constantinople",
    length: 2,
    color: "gray",
    extra: true,
  },
  {
    id: "sofia-constantinople",
    cityA: "sofia",
    cityB: "constantinople",
    length: 3,
    color: "blue",
    extra: false,
  },
  {
    id: "bucuresti-constantinople",
    cityA: "bucuresti",
    cityB: "constantinople",
    length: 3,
    color: "yellow",
    extra: false,
  },
  {
    id: "sevastopol-constantinople",
    cityA: "sevastopol",
    cityB: "constantinople",
    length: 4,
    color: "gray",
    extra: false,
  },
  {
    id: "sevastopol-bucuresti",
    cityA: "sevastopol",
    cityB: "bucuresti",
    length: 4,
    color: "white",
    extra: false,
  }
];
